@DREAMER1_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNzk4MzQ1MSwiZXhwIjoxNzQxNDM5NDUxfQ.V2qa2oB-m757NnAXYkefAWL_Vewwh526s97SYh2LuJc
@CHATROOM1_ID=67a4e29ba4b7b6ddc6ef5ac6

GET http://localhost:4000/chatRooms
Authorization: Bearer {{DREAMER1_TOKEN}}
###
GET http://localhost:4000/chatRooms/{{CHATROOM1_ID}}
Authorization: Bearer {{DREAMER1_TOKEN}}
###
GET http://localhost:4000/chatRooms/{{CHATROOM1_ID}}/chats
Authorization: Bearer {{DREAMER1_TOKEN}}
###
DELETE http://localhost:4000/chats/67a4e2f016d81504cec91f72
Authorization: Bearer {{DREAMER1_TOKEN}}
###
POST http://localhost:4000/chatRooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzc3MjU0NzUsImV4cCI6MTczNzgxMTg3NX0.Q6afR4kJ1KtTbabL9dqtHEtT9cYSoF698ngtulSy0yY
Content-Type: application/json

{
    "otherUserId": "a08d9856-adfa-4f83-9e9a-48401f3d0ef3"
}
###
POST http://localhost:4000/chatRooms/{{CHATROOM1_ID}}/chats
Authorization: Bearer {{DREAMER1_TOKEN}}
Content-Type: application/json

{
    "content": "마지막채팅123123213"
}
###
GET http://localhost:4000/chats/6792f34d2f7696df3e742d33
###
GET http://localhost:4000/chatRooms/67a1abf23f71fe22f15b7639/chats?pageSize=30
Authorization: Bearer {{DREAMER1_TOKEN}}
