GET http://localhost:4000/planTest/8fc40908-9269-4db3-ad7d-fb6e69b0ba0d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMWEyYjNjNC1kNWU2LTc4OTAtMTIzNC01Njc4OTBhYmNkZWYiLCJpYXQiOjE3MzYyNTgxNzksImV4cCI6MTczNjg2Mjk3OX0.8KvG4FE7bGYknYfpgCf6ai_7-2xi7sZ8MiE7KM-FAwA
###
POST http://localhost:4000/planTest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0Y2I1ZTUxYi0wNzJlLTRjYTItYTRhZS1iZjQzMmVhOGVmNzYiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNjc5MDgxNSwiZXhwIjoxNzM2ODc3MjE1fQ.htENqA-fVK7a572DFnOf2pGvzi8WmQ7nmwkSqAFxt9U
Content-Type: application/json

{
  "title": "제목",
  "startDate": "2025-02-01T10:00:00.000Z",
  "endDate": "2025-02-10T10:00:00.000Z",
  "tripType": "FOOD_TOUR",
  "serviceArea": "SEOUL",
  "details": "10일간 서울 맛집 탐방.",
  "address": "경상북도 경주시 불국로 385 (불국동), 38127"
}
###
POST http://localhost:4000/planTest/9f0a48f7-ace2-47d5-b7a8-3f290cd9c25f/quotes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJpYXQiOjE3MzY2MDQ0MTEsImV4cCI6MTczNzIwOTIxMX0.-eqbbKywgkiLltw8lF7NOFxytanxIQTtRHQ8OEYkE3M
Content-Type: application/json

{
    "price": 200,
    "content": "제가 제일 잘해요"
}
###
PATCH http://localhost:4000/planTest/b4f4db1e-b32d-44f6-9026-d74c38b8d899/assign
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1NTVkNDYzZS0zN2I2LTQxMGItOTA2MS0xMWE5ZDY4MjJiZGQiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNjg0Mjg5OSwiZXhwIjoxNzM2OTI5Mjk5fQ.fsskjPMXimUlxvzSRX68eSguj5laFVq8e0Esd4HFQYo
Content-Type: application/json

{
  "assigneeId": "ef846519-2b73-4be4-807e-f6ef1c07eb60"
}
###
GET http://localhost:4000/planTest/b4f4db1e-b32d-44f6-9026-d74c38b8d899
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1NTVkNDYzZS0zN2I2LTQxMGItOTA2MS0xMWE5ZDY4MjJiZGQiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNjg0Mjg5OSwiZXhwIjoxNzM2OTI5Mjk5fQ.fsskjPMXimUlxvzSRX68eSguj5laFVq8e0Esd4HFQYo

###
DELETE http://localhost:4000/planTest/b4f4db1e-b32d-44f6-9026-d74c38b8d899
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1NTVkNDYzZS0zN2I2LTQxMGItOTA2MS0xMWE5ZDY4MjJiZGQiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNjg0Mjg5OSwiZXhwIjoxNzM2OTI5Mjk5fQ.fsskjPMXimUlxvzSRX68eSguj5laFVq8e0Esd4HFQYo
