GET http://localhost:3100/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMWIyYzNkNC1lNWY2LTc4OTAtYWJjZC0xMjM0NTY3ODkwZWYiLCJpYXQiOjE3MzY0MTA2MjAsImV4cCI6MTczNzAxNTQyMH0.QSEffVkwc-geOT4ftwTfIfQKNvd_EMfXa424F6pH0oA"

###
PATCH http://localhost:3100/notifications/677e7b8a49b858d2516eb42a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMWIyYzNkNC1lNWY2LTc4OTAtYWJjZC0xMjM0NTY3ODkwZWYiLCJpYXQiOjE3MzYzMjYzNTEsImV4cCI6MTczNjkzMTE1MX0.4ZB7HY3JINOcnqxJs7zNzABb1KFpkcB66vlAnU6hQY8
