GET http://localhost:3100/notification/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMWIyYzNkNC1lNWY2LTc4OTAtYWJjZC0xMjM0NTY3ODkwZWYiLCJpYXQiOjE3MzYzMjYzNTEsImV4cCI6MTczNjkzMTE1MX0.4ZB7HY3JINOcnqxJs7zNzABb1KFpkcB66vlAnU6hQY8

###
POST http://localhost:3100/notification/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMWIyYzNkNC1lNWY2LTc4OTAtYWJjZC0xMjM0NTY3ODkwZWYiLCJpYXQiOjE3MzYzMjYzNTEsImV4cCI6MTczNjkzMTE1MX0.4ZB7HY3JINOcnqxJs7zNzABb1KFpkcB66vlAnU6hQY8

###
PATCH http://localhost:3100/notification/677e7b8a49b858d2516eb42a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMWIyYzNkNC1lNWY2LTc4OTAtYWJjZC0xMjM0NTY3ODkwZWYiLCJpYXQiOjE3MzYzMjYzNTEsImV4cCI6MTczNjkzMTE1MX0.4ZB7HY3JINOcnqxJs7zNzABb1KFpkcB66vlAnU6hQY8
