GET http://localhost:4000/plans/b4f4db1e-b32d-44f6-9026-d74c38b8d899
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMWEyYjNjNC1kNWU2LTc4OTAtMTIzNC01Njc4OTBhYmNkZWYiLCJpYXQiOjE3MzYyNTgxNzksImV4cCI6MTczNjg2Mjk3OX0.8KvG4FE7bGYknYfpgCf6ai_7-2xi7sZ8MiE7KM-FAwA
###
GET http://localhost:4000/plans
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMWIyYzNkNC1lNWY2LTc4OTAtYWJjZC0xMjM0NTY3ODkwZWYiLCJpYXQiOjE3MzYyNjUwODgsImV4cCI6MTczNjg2OTg4OH0.8F7RMB-TuYMTIiWc-SXUIGeH060Z0zHAmSSlTammFMA
###
GET http://localhost:4000/plans
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmMWEyYjNjNC1kNWU2LTc4OTAtMTIzNC01Njc4OTBhYmNkZWYiLCJpYXQiOjE3MzYyNjg1NjQsImV4cCI6MTczNjg3MzM2NH0.WicixKjBHGDt5cKcACMMSllpRP1pF_zt4bKAky-bS5o
###
DELETE http://localhost:4000/plans/b4f4db1e-b32d-44f6-9026-d74c38b8d899
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJkNGU1ZjY3OC05MGFiLWNkZWYtMDEyMy00NTY3ODkwMTIzY2QiLCJpYXQiOjE3MzYyNzIyMjUsImV4cCI6MTczNjg3NzAyNX0.y7CJdvzs6oW93QWLwO-c7f4CoGIzWGTq65rB3Vo1Ne4
###
