@MAKER1_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzc5ODEyMjEsImV4cCI6MTczODA2NzYyMX0.-s307NREt3w4RebhsPdKGCujVMbRG2PS0mPAlQ1yWHY
@DREAMER1_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNzk4MTI1MiwiZXhwIjoxNzM4MDY3NjUyfQ.z7yDvGxHVx4XAOa6YSpjP0mOuvE3GyHf8JD8QpqPZCI
GET http://localhost:4000/plans/maker
Authorization: Bearer {{MAKER1_TOKEN}}
###
GET http://localhost:4000/plans/dreamer?status=PENDING
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNzEyOTk2MCwiZXhwIjoxNzM3MjE2MzYwfQ.2o7m9QnpwhHU4otm8L-MapayoJWBsz1CTYnKQ2fQRTM
###
POST http://localhost:4000/plans
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNzk0MjYwNywiZXhwIjoxNzM4MDI5MDA3fQ.a5Gj9r31KxzRNT8c9BQzVQ7nTVd_dDo7HuWY6ocSNwE
Content-Type: application/json

{
    "title": "제목",
    "tripDate": "2025-01-19T00:00:00.000Z",
    "tripType": "FOOD_TOUR",
    "serviceArea": "SEOUL",
    "details": "상세내용"
}
###


GET http://localhost:4000/plans/dreamer?status=OVERDUE?keyword=제목
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNzIxMjc2OSwiZXhwIjoxNzM3Mjk5MTY5fQ.SrI-qFEw1ngiNEanTNWry9V9kpg0xqlbI0zVWUqjsEY
###
