GET http://localhost:4000/plans/maker
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0OWJlNjFiOC0wOTA1LTQ0OGEtODUzNC1mZTViMWEwMDA0YzIiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3MzcxMTcxNjgsImV4cCI6MTczNzIwMzU2OH0.StFvGxN_ukX73ixgKIOrgFiqQuuRlaHQLj_bxNVBkGo
###
GET http://localhost:4000/plans/dreamer?status=PENDING
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNzEyOTk2MCwiZXhwIjoxNzM3MjE2MzYwfQ.2o7m9QnpwhHU4otm8L-MapayoJWBsz1CTYnKQ2fQRTM