@HOST_NAME=http://localhost:4000/quotes
@MAKER1_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzc5ODM0MjYsImV4cCI6MTc0MTQzOTQyNn0.v5caBNbWAusy25h275WtSiJwYXPqyFC8vWPG3fO6r7E
@MAKER3_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhMDhkOTg1Ni1hZGZhLTRmODMtOWU5YS00ODQwMWYzZDBlZjMiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzg2Nzc3NjAsImV4cCI6MTc0MjEzMzc2MH0.SFh1raM_FaliSjm3QlqJYR0OMgzasmc9_8Qj3Nyk5YI
@DREAMER1_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNzk4MzQ1MSwiZXhwIjoxNzQxNDM5NDUxfQ.V2qa2oB-m757NnAXYkefAWL_Vewwh526s97SYh2LuJc
@DREAMER2_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1NTVkNDYzZS0zN2I2LTQxMGItOTA2MS0xMWE5ZDY4MjJiZGQiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczODY3NzUzMCwiZXhwIjoxNzQyMTMzNTMwfQ.XuLkyfKlskKRMfeABpwVEBCs0D0vuLyszKbef9V3m3k
@PLAN1_ID=16865772-f792-4bb6-8ac8-504fcb4064e3
@PLAN2_ID=6d201a98-1d06-4497-806a-fa123599019a
@QUOTE1_ID=a6d79d0c-c834-498a-a0bd-e4727ee938f5
@QUOTE2_ID=45ec04f9-a890-4992-adca-7f309a5b2cdc
@CONFIRMED_QUOTE_ID = 2f7ae418-6114-40ce-a55e-fb0504040613
GET http://localhost:4000/plans/{{PLAN2_ID}}/quotes
Authorization: Bearer {{DREAMER1_TOKEN}}
###드리머의 견적 리스트
GET http://localhost:4000/quotes?isSent=true
Authorization: Bearer {{MAKER1_TOKEN}}
###메이커의 견적 리스트
GET http://localhost:4000/quotes/{{QUOTE1_ID}}
Authorization: Bearer {{DREAMER1_TOKEN}}
###메이커의 견적 상세보기
GET http://localhost:4000/quotes/{{CONFIRMED_QUOTE_ID}}
Authorization: Bearer {{DREAMER2_TOKEN}}
###드리머의 견적 상세보기
GET {{HOST_NAME}}/{{CONFIRMED_QUOTE_ID}}
Authorization: Bearer {{MAKER3_TOKEN}}
###
PATCH {{HOST_NAME}}/{{QUOTE1_ID}}
Authorization: Bearer {{DREAMER1_TOKEN}}