POST http://localhost:3100/user/signup
Content-Type: application/json

{
	"user": {
		"role": "DREAMER",
	"nickName": "dagdsg",
	"email": "asdfdfasd@naver.com",
	"password": "123456789",
	"phoneNumber": "01012345678"
	},
	"profile": {
		"image": "DEFAULT_1",
		"tripTypes": ["FOOD_TOUR"],
		"serviceArea": ["SEOUL", "INCHEON"]
	}
}

###
POST http://localhost:3100/user/login
Content-Type: application/json

{
	"email": "asdfdfasd@naver.com",
	"password": "12345678"
}

###
PATCH http://localhost:3100/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3ZDI5ZWRmNi1iMWQxLTQxNWEtOWI3OS1jNWU2NGRmY2E3YmEiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNjc1NzM2NCwiZXhwIjoxNzM2ODQzNzY0fQ.gkcFRuf3Il8_fvyJTHJYbdo1jwB4IoeANWWalIO6Jnk
Content-Type: application/json

{
	"nickName": "닉네임 수정 테스트"
}

###
POST http://localhost:3100/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwZWY3MmFjNy1hZmViLTQyNzItYjc2Yi1iNjRkOTNhZTc4NzkiLCJpYXQiOjE3MzYyMjc3NzgsImV4cCI6MTczNjMxNDE3OH0.15V3Va4QzmCeUH2ua3Zt5wM7NVp5v9cfwAlHnTtKpME
Content-Type: application/json

{
	"makerId": "5d0b3e03-d70c-4c15-bd30-cfd805823173"
}

###
DELETE http://localhost:3100/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwZWY3MmFjNy1hZmViLTQyNzItYjc2Yi1iNjRkOTNhZTc4NzkiLCJpYXQiOjE3MzYyMjc3NzgsImV4cCI6MTczNjMxNDE3OH0.15V3Va4QzmCeUH2ua3Zt5wM7NVp5v9cfwAlHnTtKpME
Content-Type: application/json

{
	"makerId": "5d0b3e03-d70c-4c15-bd30-cfd805823173"
}

###
POST http://localhost:4000/users/login
Content-Type: application/json

{
	"email": "maker3@test.com",
	"password": "12345678"
}
###
POST http://localhost:4000/users/login
Content-Type: application/json

{
	"email": "dreamer2@test.com",
	"password": "12345678"
}
###
