export const ServiceAreaValues = {
  SEOUL: 'SEOUL',
  BUSAN: 'BUSAN',
  INCHEON: 'INCHEON',
  DAEGU: 'DAEGU',
  DAEJEON: 'DAEJEON',
  GWANGJU: 'GWANGJU',
  ULSAN: 'ULSAN',
  SEJONG: 'SEJONG',
  GYEONGGI: 'GYEONGGI',
  GANGWON: 'GANGWON',
  CHUNGBUK: 'CHUNGBUK',
  CHUNGNAM: 'CHUNGNAM',
  JEONBUK: 'JEONBUK',
  JEONNAM: 'JEONNAM',
  GYEONGBUK: 'GYEONGBUK',
  GYEONGNAM: 'GYEONGNAM',
  JEJU: 'JEJU'
} as const;

export type ServiceArea = keyof typeof ServiceAreaValues;
